### ISSUE TITLE
Suchfeld im Frontend mit Funktion ausstatten

### ISSUE THREAD

**Issue by dbaumgarten** [ringvorlesung2019mgm/twitter-bingo#11]
Im Moment tut das Suchfeld im Frontend exakt nichts (außer hübsch auszusehen).
Es sollte aber für den API-Aufruf der Tweetliste benutzt werden.

**Comment by dbaumgarten** [comment]
Das Suchfeld funktioniert noch nicht. Ich glaube du hast vergessen die geänderte javascript-Datei zu pushen. In deinen commits sehe ich nur die index.html und einige Dateien vo IntelliJ.

**Comment by stdoro** [comment]
ja der commit ist schiefgegangen. Ich bin gerade nochmal dran. Aber es hat schonmal funktioniert :D

**Comment by dbaumgarten** [comment]
Jetzt funktioniert alles :+1:
