### ISSUE TITLE
Webapp-Backend-TweetStream

### ISSUE THREAD

**Issue by dbaumgarten** [ringvorlesung2019mgm/twitter-bingo#2]
- Webapp anlegen
- API-Endpunkt für TweetStream 

- Bekommt query als HTTP_GET-Parameter.
- Startet Producer (wenn nötig)
- Liest aus Kafka
- Schreibt mittels HTTP1.1 chunked response an frontend
- Stoppt producer nach Ende der Verbindung

**Comment by dbaumgarten** [comment]
@jpeinuni wie ist denn der Stand hierzu momentan?
Solange das hier nicht wenigstens grundlegend fertig ist kann nirgends weiter gearbeitet werden.

**Comment by jpeinuni** [comment]
>     * Webapp anlegen - Done
> 
>     * API-Endpunkt für TweetStream - Done
> 
>     * Bekommt query als HTTP_GET-Parameter. - Done (HTTP_POST)
> 
>     * Startet Producer (wenn nötig) - Done (StreamManager)
> 
>     * Liest aus Kafka - TODO (Demo, da Analyser nicht eingbaut)
> 
>     * Schreibt mittels HTTP1.1 chunked response an frontend - DONE
> 
>     * Stoppt producer nach Ende der Verbindung - TODO

**Comment by dbaumgarten** [comment]
So wie du den StreamManager zurzeit verwendest ( https://github.com/ringvorlesung2019mgm/twitter-bingo/blob/cf5144b4fcd66fe20855519af89d03ddf1ded1f2/producer/src/main/java/webapps/TweetStreamServlet.java#L26 ) hilft das überhaupt nichts. 
Das gemeinsame Nutzen von Streams (was der StreamManager ermöglichen soll) funktioniert nur, wenn alle User die gleiche Instanz des Managers nutzen. Im Moment hat aber jede Servlet-Instanz ihren eigenen StreamManager.

**Comment by jpeinuni** [comment]
StreamManager ist jetzt ein Singleton.

**Comment by dbaumgarten** [comment]
Wie ist der aktuelle Stand? Können wir den API-Branch bald mal wieder in master mergen?

**Comment by jpeinuni** [comment]
Bin dabei!

**Comment by jpeinuni** [comment]
Hab es in master gemergt. Der letzte Punkt ist bereits implementiert, wird aber unter #12 commited.
Mach dann hier mal zu.
