### ISSUE TITLE
Zeichenkodierungfeher bei Tweet-Anzeige im Frontend

### ISSUE THREAD

**Issue by dbaumgarten** [ringvorlesung2019mgm/twitter-bingo#28]
Umlaute in Tweets werden im Frontend als � dargestellt.

**Comment by dbaumgarten** [comment]
Btw. die Umlaute kommen richtig aus der api (siehe: http://localhost:8080/producer/api/TweetStream?q=diespahnfee ). Das Problem muss also irgendwo bei der Anzeige liegen.

**Comment by jpeinuni** [comment]
Tweets werden glaube in der logic.js als UTF8 nach Json geparst. Da liegt
eine Fehlerquelle

**Comment by dbaumgarten** [comment]
Der Ursprung des Problems war folgender:
Die HTML-Datei ist UTF-8 kodiert. Deshalb müssen auch alle dort per Javascript eingefügten Zeichen UTF-8 kodiert sein, sonst gibts Zeichensalat.
Das TweetStreamServlet hat nun aber (gemäß der Java-Servlet-Spezifikation) seinen Kram ISO-8859-1 kodiert. Diese Daten in das HTML einzufügen hat die Probleme verursacht.

Das Servlet nutzt jetzt UTF-8 und setzt die korrekten Header. Problem gelöst :+1:
