### ISSUE TITLE
Mehrere Hashtags == Mehrere Kafka-Tweets

### ISSUE THREAD

**Issue by jpeinuni** [ringvorlesung2019mgm/twitter-bingo#33]
Sollte sich herausstellen das die Sentiment-Analyse ein Performance-Engpass ist, da Tweets stellenweise mehrfach analysiert werden (z.B. da sie mehrere Hashtags enthalten und somit mehreren verschiedenen Filterkriterien entsprechen) könnte man einen Cache-Server (Memcached, Redis) hinzuziehen. 

Wir wissen mittlerweile, das die Sentiment Analyse nicht der Engpass ist, aber wie gehen wir mit dem beschriebenen Problem (mehrere Hashtags, die gleichzeitig ausgewertet werden) um?

**Comment by dbaumgarten** [comment]
Ich steh gerade auf dem Schlauch. Welches Problem?

**Comment by dbaumgarten** [comment]
???
