### ISSUE TITLE
Frontend - Diagramm anzeigen

### ISSUE THREAD

**Issue by dbaumgarten** [ringvorlesung2019mgm/twitter-bingo#38]
- Tweetdaten über gewünschte Zeitintervalle aggregieren
- Diagramm anzeigen

Ich würde vorschlagen, wir vergessen d3 und nehmen einfach das hier: https://canvasjs.com/html5-javascript-line-chart/

**Comment by dbaumgarten** [comment]
Das sieht doch schon recht hübsch aus.
Die Animation sollte am besten ausgeschaltet werden, sonst startet die jedes mal wenn ein neuer tweet reinkommt.
Und es wäre wahrscheinlich besser Durchschnittswerte anzuzeigen anstatt einzelwerte. Im Moment ist die Kurve einfach nicht sehr aussagekräftig.

**Comment by stdoro** [comment]
Ja. Das kommt noch. Das war erstmal nur das, was ich gestern so geschafft habe.

**Comment by stdoro** [comment]
Wie sollen die Werte schlussendlich jetzt aggregiert werden?

**Comment by dbaumgarten** [comment]
Ich denke am sinnvollsten wäre eine Art sliding window, also einfach immer den durschnitt der letzten n (2-5?) Tweets.

**Comment by dbaumgarten** [comment]
Damit wäre das Issue jetzt erledigt und kann geschlossen werden, oder?

**Comment by stdoro** [comment]
Ja
