### ISSUE TITLE
Backend - Hashtag zum ersten mal anfragen fehlerhaft

### ISSUE THREAD

**Issue by stdoro** [ringvorlesung2019mgm/twitter-bingo#45]
Wenn man zum ersten Mal einen neuen Hashtag sucht, kommen die Tweets nicht in chronologischer Reihenfolge an. Im Tweet-Window sind sie teilweise in umgekehrter Reihenfolge, teilweise mit einem falsch eingeordneten Tweets. Im Diagramm sieht man die Ausreißer auch manchmal. Ab der zweiten Anfrage tritt der Fehler nicht mehr auf.

<img width="945" alt="diagramm" src="https://user-images.githubusercontent.com/39804227/50549563-58a2c700-0c5f-11e9-8724-ae5c44d1545c.PNG">
<img width="468" alt="latest tweets" src="https://user-images.githubusercontent.com/39804227/50549564-58a2c700-0c5f-11e9-8869-f75444e28905.PNG">

**Comment by dbaumgarten** [comment]
Das problem war, dass beim ersten Aufruf die historischen Streams auch über den mongodb changestream geliefert werden. Dieser sortiert nicht, sondern gibt tweets in der Reihenfolge zurück in der sie in der db eingehen. Und da die twitter api die tweets in der "falschen" Reihenfolge liefert kam es zu diesem problem.
Bei späteren Aufrufen kommen die historischen Tweets aus nem "normalen" DB-query, dass die Ergebnisse direkt richtig sortiert ausgibt.

Die "Vertauschungen" entstehen an der Stelle wo historische (falsch sortierte) und neue (richtig sortierte) tweets aufeinander treffen. 

Der letzte Commit sollte beides beheben.
