### ISSUE TITLE
Tweets als JSON

### ISSUE THREAD

**Issue by dbaumgarten** [ringvorlesung2019mgm/twitter-bingo#6]
Zurzeit werden nur die Texte der Tweets als String in Kafka gespeichert.
Im Moment brauchen wir zwar nicht viel mehr, aber für die Zukunft wäre es besser wenn das komplette Tweet-Object (incl. username, datum etc.) als JSON serialisiert und in Kafka gespeichert wird.

**Comment by dbaumgarten** [comment]
Der Python-Teil dieses Issues ist erledigt. Falls der Java-Teil auch fertig ist, kann das Issue geschlossen werden.

**Comment by jpeinuni** [comment]
Java ist soweit auch fertig.
