### ISSUE TITLE
Webserver liefert Frontend-Dateien aus

### ISSUE THREAD

**Issue by dbaumgarten** [ringvorlesung2019mgm/twitter-bingo#9]
Der Webserver soll auch alle Dateien für das Frontend (html, css, js, etc.) an den User ausliefern.

Am besten wäre es das gradle-script so zu modifizieren, dass es beim builden automatisch den aktuellen Inhalt des Frontend-ordners an die richtige Stelle (z.B. src/main/webapp/index.html) kopiert.

Wahrscheinlich wäre es am Besten die API-Endpunkte in einen eigenen Unterpfad (localhost:8080/api/endpunkt) zu verlegen um API und Frontend sauber zu trennen.

**Comment by jpeinuni** [comment]
Das gradle-script brauchen wir nicht, der files können genau so gut von vornherein dort liegen. 

Adressen zum Testen der Anwendung sind localhost:8080/producer/api/TweetStream für den Endpunkt und localhost:8080/producer für die index.html

Hab das auf branch api grade probiert, können ja morgen gucken ob es allen so passt

**Comment by dbaumgarten** [comment]
Ich hatte den Eindruck, dass das soweit ganz gut funktioniert. Spricht irgendwas dagegen das nach master zu übernehmen?
